blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('home/', views.PostListView.as_view(), name="blog_home"),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name="post_detail"),
    path('post/new/', views.PostCreateView.as_view(), name="post_new"),
    path('post/<int:pk>/update/', views.PostUpdateView.as_view(), name="post_update"),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name="post_delete"),
    path('user/<str:username>/', views.UserPostListView.as_view(), name="user_posts"),
    path('handle_email/', views.handle_feedback_email, name="handle_email"),
   # path('search/', views.search, name="search"),
    
]

dg_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views
from django.contrib.auth import views as auth_views
from searches.views import search_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),

    path('search/', search_view),

    path('register/', user_views.register, name='register'),
    path('login/', user_views.LogInUser.as_view(), name='login'),
    path('logout/', user_views.LogOutUser.as_view(), name='logout'),
    path('profile/', user_views.profile, name='profile'),

    path('password-reset/', user_views.ResetPassword.as_view(), name='password_reset'),
    path('password-reset/done/', user_views.ResetPasswordDone.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', user_views.ConfirmPasswordReset.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', user_views.CompletePasswordReset.as_view(), name='password_reset_complete'),

     path('password_change/',auth_views.PasswordChangeView.as_view(template_name='users/password_change_form.html'),
            name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),
            name='password_change_done'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class PostQuerySet(models.QuerySet):
    def search(self, query):
        return self.filter(content__icontains=query)

class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().search(query)


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    view_count = models.PositiveIntegerField(default=0)

    objects = PostManager()

    def __str__(self):
        return f'{self.title}: by {self.author}'

    
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.created}'

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body',)

class EmailFeedbackForm(forms.Form):
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import View
from django.views.generic import (ListView, DetailView, CreateView,
    UpdateView, DeleteView, FormView
)
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib import messages
from django.core import serializers
from django.http import JsonResponse
from django.core.mail import send_mail
from .models import Comment, Post
from .forms import CommentForm, EmailFeedbackForm


def welcome(request):
    return render(request, 'blog/welcome.html')

class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 4
    

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'content')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ('title', 'content')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("blog:blog_home")

    def test_func(self):
        post = self.get_object()

        if post.author == self.request.user:
            return True
        return False


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')


class PostDisplayView(DetailView):
    model = Post
    
    def get_object(self):
        object = super(PostDisplayView, self).get_object()
        object.view_count += 1
        object.save()
        return object

    def get_context_data(self, **kwargs):
        context = super(PostDisplayView, self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post=self.get_object())
        context['form'] = CommentForm()
        return context


class CommentView(FormView):
    form_class = CommentForm
    template_name = 'blog/post_detail.html'

    def form_valid(self, form):
        if self.request.is_ajax:    
            post = Post.objects.get(pk=self.kwargs['pk'])
            form.instance.post = post
            obj = form.save()
            res = [{"name": obj.name, "created": obj.created, "body": obj.body}]
            return JsonResponse(res, safe=False)
        return super(CommentView, self).form_valid(form)
        
    def get_success_url(self):
       return reverse('blog:post_detail', kwargs={'pk': self.kwargs['pk']})


class PostDetailView(View):
    def get(self, request, *args, **kwargs):
        view = PostDisplayView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = CommentView.as_view()
        return view(request, *args, **kwargs)

def handle_feedback_email(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            sender_email = request.user.email
            message = request.POST['message']
            send_mail("Viewer Feedback",
                    message,
                    sender_email,
                    ['victory@hotmail.io'],
                    fail_silently=False
            )
            return redirect('blog:blog_home')
    else:
        if request.method == 'POST':
            sender_email = request.POST['email']
            message = request.POST['message']
            send_mail("Viewer Feedback",
                        message,
                        sender_email,
                        ['victory@hotmail.io'],
                        fail_silently=False
                    )
            return redirect('blog:blog_home')
            

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">

  <title>Blog_er - {% block title %}{% endblock title %}</title>
</head>

<body>
  <div class="whole-back">
    {% include 'blog/nav-bar.html'%}

    <div class="container">
      <div style="margin-top: 70px;">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
        {% endif %}
        {% block content%}
        {% endblock content %}
      </div>
    </div>

  </div>
    {% include 'blog/footer.html' %}
 

  <script src="{% static 'js/jquery-3.5.1.slim.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/all.js' %}"></script>

  {% block scripts %}
  {% endblock scripts %}

</body>

</html>

blog/templates/blog/footer.html
<div class="footer">
    <div class="footer-header">
        <p>&copy;Blog_er 2020</p>
    </div>

    <div class="container">
        <div class="footer-content">
            <div class="row">
                <div class="col-md-4">
                    <p>Contact</p>
                    <span>
                        <i class="fa fa-envelope">admin34@bloger.com</i>
                    </span>
                </div>

                <div class="col-md-4">
                    <p><a href="#">Our Policy</a></p>
                </div>

                <div class="col-md-4">
                    <p><a href="#">About</a></p>
                </div>

            </div>
        </div>
    </div>


</div>

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block title %}Home{% endblock title %}

{% block content %}


<div class="row">
    <div class="col-md-8">
        <form action="/search/">
            {% csrf_token %}
            <input type="search" placeholder="Enter your search here" name="q" aria-label="search" class="form-control">
            <button class="btn btn-outline-success mt-2 mb-5">Search</button>
        </form>
        {% for post in posts %}
        <article class="article">
            <span>
                <p class="author"><a href="{% url 'blog:user_posts' post.author.username %}">{{ post.author }}</a> | on
                    {{ post.date_posted }} | &#x1f441 {{ post.view_count }} Views</p>
            </span>
            <h3><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h3>
            <img src="{{post.author.profile.p_pic.url}}" class="rounded-circle z-depth-0" alt="avatar image"
                height="35">
            <p class="mr-10">{{ post.content|truncatewords:30 }}....<a href="{% url 'blog:post_detail' post.pk %}">Read
                    More</a></p>
        </article>

        <hr>
        {% endfor %}

        {% if is_paginated %}

        {% if page_obj.has_previous %}
        <a class="btn btn-outline-info" href="?page=1">First</a>
        <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
        <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %} <a class="btn btn-outline-info"
            href="?page={{ num }}">{{ num }}</a>
            {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
            <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}

            {% endif %}
    </div>


    <div class="col-md-4">
        <div class="content-section mt-2">
            <h4>Please email us with your feedbacks</h4>
                <form action="{% url 'blog:handle_email' %}" method="POST">
                    {% csrf_token %}
                    {% if not request.user.is_authenticated %}
                    Your Email: <input class="form-control" type="email" name="email">
                    Message: <textarea id="" class="form-control" name="message"></textarea>
                    {% else %}
                    Message: <textarea id="" class="form-control" name="message"></textarea>
                    {% endif %}
                    <button type="submit" class="btn btn-outline-primary btn-lg mt-2">Send</button>
                </form>
        </div>
    </div>
</div>

{% endblock content %}

blog/templates/blog/nav-bar.html
<!-- <nav class="mb-1 navbar navbar-expand-lg fixed-top  lighten-1" >  -->
    <nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-custom-2">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:welcome' %}">Blog_er</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
            aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:blog_home' %}"><i class="fa fa-home"></i>
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
           
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:post_new' %}">New Post</a>
                </li>
                {% endif %}     

            </ul>
            <ul class="navbar-nav ml-auto nav-flex-icons">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                </li>

                <li class="nav-item avatar">
                    <a class="nav-link p-0" href="{% url 'profile' %}">
                        <img src="{{ user.profile.p_pic.url }}" class="rounded-circle z-depth-0" alt="avatar image" height="35">
                    </a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">SignIn</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">SignUp</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}


{% block content %}
<div class="row">
    <div class="col-sm-8 mx-auto">
        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Post Delete</legend>
                <h3>Are you sure you want to delete this post "{{ object.title }}"</h3>
                <div class="form-group">
                    <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                    <a href="{% url 'blog:post_detail' object.pk %}" class="btn btn-outline-secondary">Cancel</a>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock%}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{ post.title }} {% endblock title %}

{% block content %}
<div class="row">
    <div class="col-sm-10 mx-auto">

        <article>
            <span>
                <p class="author"><a href="{% url 'blog:user_posts' post.author.username%}">{{ post.author }}</a> | on
                    {{ post.date_posted }} | &#x1f441 {{ post.view_count }} Views</p>
            </span>
            <h2>{{ post.title }}</h2>
            <p>{{ post.content }}</p>
        </article>

        <div>
            {% if post.author == request.user %}
            <a href="{% url 'blog:post_update' post.pk %}" class="btn btn-outline-secondary btn-sm">Update</a>
            <a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-danger btn-sm">Delete</a>
            {% endif %}
        </div>
        <hr>
        <div class="comment-list">

            <h4>Comments</h4>
            {% for comment in comments %}
           
            <div class="comment">
                <div class="alert alert-primary">
                    <p><b>{{ comment.name }}</b> on {{ comment.created }}</p>
                    <p>{{ comment.body }}</p>
                </div>
            </div>

            {% empty %}
            <div class="no-comment">
                <p>No comments yet!</p>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-sm-2 mx auto">
        <h5>Comment here</h5>
        <form action="" method="POST" id="comment-form">
            {% csrf_token %}
            {{form|crispy}}
            <button class="btn btn-outline-success">Post Comment</button>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-sm-2">

    </div>
</div>
{% endblock content %}

{% block scripts %}
<!-- <script>
    let commentForm = document.getElementById("comment-form")

    commentForm.addEventListener('submit', (e) => {
        e.preventDefault();
        let name = document.querySelector("#id_name").value;
        let email = document.querySelector("#id_email").value;
        let content = document.querySelector("#id_body").value;

        if (name && email && content) {
            console.log("Form submitted successfully!")
            let formData = new FormData(commentForm);

            let csrfValue = document.getElementsByName("csrfmiddlewaretoken")[0].value

            fetch("{% url 'blog:post_detail' post.pk %}", {
                method: "POST",
                headers: {
                    'X-CSRFToken': csrfValue,
                    'X-Requested-With': 'XMLHttpRequest'
                },
                body: formData
            }).then((response) => {
                return response.json()
            }).then((data) => {
                commentForm.reset()

                console.log(data);
                    
                });

                let instance = JSON.parse(data["new_comment"]);
                let fields = instance[0]["fields"];
                let commentList = document.querySelector(".comment-list");
                let noComment = document.querySelector(".no-comment");

                if (noComment) {
                    commentList.removeChild(noComment);
                }

                commentList.innerHTML = + `

                    <div class="comment">
                        <div class="alert alert-primary">
                            <p><b>${fields['name']}</b> Just now</p>
                            <p>${fields['body']}</p>
                        </div>
                    </div>

                         `

            }).catch((error) => {
                console.error("Error", error)
            })

        } else {
            console.log("Please enter all the form fields");
        }
    })
</script> -->
{% endblock scripts %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-md-8">

        <form action="" method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Post</button>
                </div>
            </fieldset>
        </form>
    </div>

    <div class="col-md-4">
        <div class="content-section mt-5">
            <h3>Our Section</h3>
            <hr>
            <p>Latest post</p>
            <hr>
            <p>Calenders</p>
            <hr>
            <p>Lifestyle</p>
            <hr>
        </div>
    </div>
</div>
{% endblock%}

blog/templates/blog/user_posts.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="col-sm-6 mx-auto">
    <h2>Posts by : {{ view.kwargs.username }} - ({{ page_obj.paginator.count }})</h2>
    {% for post in posts %}
    <article>
        <!-- <p class="author"><a href="{% url 'blog:user_posts' post.author.username %}">{{ post.author }}</a> on {{ post.date_posted }}</p> -->
        <p class="author">{{ post.author }} on {{ post.date_posted }}</p>
        <h3><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h3>
        <p>{{ post.content }}</p>
    </article>
    <hr>
    {% endfor %}

    {% if is_paginated %}

    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info" href="?page=1">First</a>
    <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
    <a class="btn btn-info" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a class="btn btn-outline-info" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
    <a class="btn btn-outline-info" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}

    {% endif %}
</div>
{% endblock content %}

blog/templates/blog/welcome.html
{% extends 'blog/base.html' %}
{% load static %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="header">
    <h3 >Welcome to Blog_er</h3>
    <p class="everything">Everything Tech related is here!!</p>
    <a class="btn btn-outline-primary btn-lg" href="{% url 'blog:blog_home' %}">Continue</a>
    <p class="note">Please note that if you are not signed in you wont be able to create your own posts.</p>
</div>

{% endblock %}